Установим и импорируем библиотеку NumPy, она потребуется нам для работы с матрицами

In [658]:
%pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


Создадим матрицу с шестью векторами признаков, а также столбец с правильной бинарной классификацией этих объектов (столбец правильный ответов).

In [659]:
training_inputs = np.array ([
    [0,0,1],
    [1,0,1],
    [1,0,0],
    [0,1,1],
    [0,1,0],
    [1,1,1]
])

training_outputs = np.array([[0,2,1,0,0,1]]).T # метод T транспонирует матрицу: превратит строку в столбец правильных ответов

In [660]:
training_outputs

array([[0],
       [2],
       [1],
       [0],
       [0],
       [1]])

Функция ```np.random.random((M,N))``` возвращает матрицу случайных чисел из диапазона [0, 1), состояющую из M столбцов и N строк. Если надо получить вектор (по сути одну строку маттрицы), то во второй арргумент N мы можем передать 1.

In [661]:
weights = np.random.random((3,1)) # создаем вектор весов, для начала со случайными значениями

print("Веса до обучения (случайные):")
print(weights)

Веса до обучения (случайные):
[[0.57838961]
 [0.4081368 ]
 [0.23702698]]


Создадим функцию активации (для этого будем использовать сигмоиду):

In [662]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

Запустим цикл обучения:

In [663]:
for i in range(1000):
   outputs = sigmoid(np.dot(training_inputs, weights)) # вычисляем выходное значение, для простоты тут не используем смещение, только веса
   errors = training_outputs - outputs # вычисляем значения ошибок для каждого вектора в выборке, для простоты берем разность между вычисленным и целевым значением
   adjustments = np.dot(training_inputs.T, errors * outputs) # создаем набор корректировок для каждого веса
   weights = weights + adjustments # применяем корректировки

print("Веса после обучения (скорректированные):")
print(weights)

Веса после обучения (скорректированные):
[[1001.20744368]
 [  -9.86167242]
 [   6.66308546]]


Проверим какие результаты вычислит нейросеть для тестовой выборки:

In [664]:
print(sigmoid(np.dot(np.array([[1,1,0],[0,1,0]]), weights)))

[[1.00000000e+00]
 [5.21323671e-05]]
